num_worktrees = 8

[[tests]]
name = "check"
command = "timeout 300 nix flake check"

[[tests]]
name = "impure-tests"
# --forgreound avoids dumb TTY bullshit with QEMU, I dunno.
command = "timeout --foreground 3000 nix run .#impure-tests"